### ISSUE TITLE
Change requested host

### ISSUE THREAD

**Issue by eszymko** [wxsSteven/iotdm-client#1]
I have tryed to use RestConf.defaultProvision("dev1"); to set the destination host to dev1 but I have the following error try to create an AE:
java.net.ConnectException: Connection refused: no further information

Is requested host adresse change supported ?

**Comment by tjanciga** [comment]
Yes, it is supported. You can use also IP address instead of the name. What about "ping dev1" ?

**Comment by eszymko** [comment]
Ok so what is the method to use to modify the address ?

**Comment by tjanciga** [comment]
I mean, you can use RestConf.defaultProvision("localhost"); as well as RestConf.defaultProvision("127.0.0.1");
You can also use the same method with names/IPs from your environment if you've configured networking (DNS, IPv4/IPv6) correctly but the configuration is out of scope of this client.
